os: osx
osx_image: xcode9.2
language: swift

before_install:
- curl -sL https://raw.githubusercontent.com/rocktavious/redowl-build-tools/master/scripts/utils.sh | bash

install:
- travis_retry ./scripts/install-unity.sh

script:
- ./scripts/clean.sh
- ./scripts/build-windows.sh <PROJECT_NAME>
- ./scripts/build-osx.sh <PROJECT_NAME>
- ./scripts/build-linux.sh <PROJECT_NAME>
- ./scripts/build-webgl.sh <PROJECT_NAME>
- ./scripts/run-tests.sh <PROJECT_NAME>

after_success:
- ./scripts/export-package.sh <COMPANY_NAME> <PROJECT_NAME>